"""Canonical manufacturing Chart of Accounts for CAS (Philippine manufacturing corp).

149 accounts (146 base + 2 inter-branch clearing accounts, R-04 slice 2 + 1 Cash
Short/Over control account, R-04 slice 4) already
carrying the FS taxonomy used by the type-driven financial
statements (account_type one of: Asset, Liability, Equity, Revenue, Contra-Revenue,
Other Income, Cost of Goods Sold, Selling Expense, Administrative Expense, Other
Expense, Income Tax Expense) + Current/Non-Current classification for Assets and
Liabilities.

Hierarchy is DERIVED (a node is a PARENT/group header if it is top-level or has
children; otherwise a postable LEAF) — there is no stored is_header flag. `parent`
holds the parent account's CODE (None = top-level group).

Provenance: reconstructed from scripts/retype_manufacturing_coa.py (authoritative
codes + FS account_type + classification + grouping) plus names harvested from the
older COA seed; remaining names follow standard PH-manufacturing convention.

NOTE: as of the core-baseline rewrite, seed_minimal() no longer uses this module — it
seeds the lean general-purpose BASELINE_COA (see seed_data.py), which is what
/reset-database produces. This 149-account manufacturing COA is retained for the
demo/pitch datasets and its own type test (tests/unit/test_manufacturing_coa_types.py).
"""

MANUFACTURING_COA = [
    # ===== ASSETS - Current =====
    {'code': '10100', 'name': 'Cash and Cash Equivalents', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '10101', 'name': 'Cash on Hand', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10100'},
    {'code': '10102', 'name': 'Petty Cash Fund', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10100'},
    {'code': '10110', 'name': 'Cash in Bank - Current Account', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10100'},
    {'code': '10111', 'name': 'Cash in Bank - Savings Account', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10100'},
    {'code': '10112', 'name': 'Cash in Bank - Payroll Account', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10100'},
    {'code': '10200', 'name': 'Trade and Other Receivables', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '10201', 'name': 'Accounts Receivable - Trade', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10200'},
    {'code': '10202', 'name': 'Allowance for Doubtful Accounts', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '10200'},
    {'code': '10205', 'name': 'Notes Receivable', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10200'},
    {'code': '10210', 'name': 'Other Receivables', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10200'},
    {'code': '10211', 'name': 'Advances to Employees', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10200'},
    {'code': '10212', 'name': 'Creditable Withholding Tax', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10200'},
    {'code': '10213', 'name': 'Inter-branch Due from', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10200'},
    {'code': '10300', 'name': 'Inventories', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '10301', 'name': 'Raw Materials Inventory', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10300'},
    {'code': '10302', 'name': 'Work-in-Process Inventory', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10300'},
    {'code': '10303', 'name': 'Finished Goods Inventory', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10300'},
    {'code': '10304', 'name': 'Factory Supplies Inventory', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10300'},
    {'code': '10305', 'name': 'Goods in Transit', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10300'},
    {'code': '10400', 'name': 'Prepaid Expenses and Other Current Assets', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '10401', 'name': 'Prepaid Rent', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10400'},
    {'code': '10402', 'name': 'Prepaid Insurance', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10400'},
    {'code': '10403', 'name': 'Other Current Assets', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10400'},
    {'code': '10500', 'name': 'Input VAT', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '10501', 'name': 'Input VAT - Capital Goods', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10500'},
    {'code': '10502', 'name': 'Input VAT - Domestic Goods', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10500'},
    {'code': '10503', 'name': 'Input VAT - Services', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10500'},
    {'code': '10504', 'name': 'Input VAT - Importation', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10500'},
    {'code': '10505', 'name': 'Excess Input Tax Carry-Over', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10500'},
    {'code': '10506', 'name': 'Deferred Input Tax', 'type': 'Asset', 'classification': 'Current', 'normal_balance': 'debit', 'parent': '10500'},
    # ===== ASSETS - Non-Current =====
    {'code': '11100', 'name': 'Property, Plant and Equipment', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '11101', 'name': 'Land', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11110', 'name': 'Furniture and Fixtures', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11111', 'name': 'Accumulated Depreciation - Furniture and Fixtures', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11100'},
    {'code': '11120', 'name': 'Office Equipment', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11121', 'name': 'Accumulated Depreciation - Office Equipment', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11100'},
    {'code': '11130', 'name': 'Computer Equipment', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11131', 'name': 'Accumulated Depreciation - Computer Equipment', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11100'},
    {'code': '11140', 'name': 'Vehicles', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11141', 'name': 'Accumulated Depreciation - Vehicles', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11100'},
    {'code': '11150', 'name': 'Machinery and Equipment', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11151', 'name': 'Accumulated Depreciation - Machinery and Equipment', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11100'},
    {'code': '11160', 'name': 'Building', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11161', 'name': 'Accumulated Depreciation - Building', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11100'},
    {'code': '11170', 'name': 'Leasehold Improvements', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11171', 'name': 'Accumulated Depreciation - Leasehold Improvements', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11100'},
    {'code': '11180', 'name': 'Construction in Progress', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11100'},
    {'code': '11200', 'name': 'Intangible Assets', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '11201', 'name': 'Software', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11200'},
    {'code': '11202', 'name': 'Accumulated Amortization - Software', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': '11200'},
    {'code': '11300', 'name': 'Other Non-Current Assets', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': None},
    {'code': '11301', 'name': 'Long-term Deposits', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11300'},
    {'code': '11302', 'name': 'Deferred Tax Assets', 'type': 'Asset', 'classification': 'Non-Current', 'normal_balance': 'debit', 'parent': '11300'},
    # ===== LIABILITIES - Current =====
    {'code': '20100', 'name': 'Trade and Other Payables', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': None},
    {'code': '20101', 'name': 'Accounts Payable - Trade', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20102', 'name': 'Accounts Payable - Others', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20103', 'name': 'Accrued Expenses', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20104', 'name': 'Accrued Salaries and Wages', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20105', 'name': 'Accrued Interest Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20106', 'name': 'Advances from Customers', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20107', 'name': 'Dividends Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20108', 'name': 'Due to Related Parties', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20109', 'name': 'Other Payables', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20111', 'name': 'Inter-branch Due to', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20100'},
    {'code': '20200', 'name': 'Output VAT', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': None},
    {'code': '20201', 'name': 'Output VAT - Sales', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20200'},
    {'code': '20300', 'name': 'Withholding and Other Taxes Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': None},
    {'code': '20301', 'name': 'Withholding Tax Payable - Expanded', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20300'},
    {'code': '20302', 'name': 'Withholding Tax Payable - Compensation', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20300'},
    {'code': '20303', 'name': 'Withholding Tax Payable - Final', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20300'},
    {'code': '20304', 'name': 'Percentage Tax Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20300'},
    {'code': '20305', 'name': 'Income Tax Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20300'},
    {'code': '20400', 'name': 'Statutory Payables', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': None},
    {'code': '20401', 'name': 'Employee Loans/Deductions Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20400'},
    {'code': '20402', 'name': 'SSS Contributions Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20400'},
    {'code': '20403', 'name': 'PhilHealth Contributions Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20400'},
    {'code': '20404', 'name': 'Pag-IBIG Contributions Payable', 'type': 'Liability', 'classification': 'Current', 'normal_balance': 'credit', 'parent': '20400'},
    # ===== LIABILITIES - Non-Current =====
    {'code': '21100', 'name': 'Long-term Loans Payable', 'type': 'Liability', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': None},
    {'code': '21200', 'name': 'Bonds Payable', 'type': 'Liability', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': None},
    {'code': '21300', 'name': 'Finance Lease Liability', 'type': 'Liability', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': None},
    {'code': '21400', 'name': 'Deferred Tax Liabilities', 'type': 'Liability', 'classification': 'Non-Current', 'normal_balance': 'credit', 'parent': None},
    # ===== EQUITY =====
    {'code': '30100', 'name': 'Share Capital', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': None},
    {'code': '30101', 'name': 'Common Stock', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': '30100'},
    {'code': '30102', 'name': 'Preferred Stock', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': '30100'},
    {'code': '30103', 'name': 'Subscribed Share Capital', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': '30100'},
    {'code': '30104', 'name': 'Subscription Receivable', 'type': 'Equity', 'classification': None, 'normal_balance': 'debit', 'parent': '30100'},
    {'code': '30110', 'name': 'Additional Paid-in Capital', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': '30100'},
    {'code': '30120', 'name': 'Treasury Stock', 'type': 'Equity', 'classification': None, 'normal_balance': 'debit', 'parent': '30100'},
    {'code': '30200', 'name': 'Retained Earnings', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': None},
    {'code': '30201', 'name': 'Retained Earnings - Unappropriated', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': '30200'},
    {'code': '30202', 'name': 'Retained Earnings - Appropriated', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': '30200'},
    {'code': '30301', 'name': 'Current Year Earnings', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': None},
    {'code': '30401', 'name': 'Cumulative Translation Adjustment', 'type': 'Equity', 'classification': None, 'normal_balance': 'credit', 'parent': None},
    # ===== REVENUE =====
    {'code': '40100', 'name': 'Sales', 'type': 'Revenue', 'classification': None, 'normal_balance': 'credit', 'parent': None},
    {'code': '40101', 'name': 'Sales - Finished Goods', 'type': 'Revenue', 'classification': None, 'normal_balance': 'credit', 'parent': '40100'},
    {'code': '40102', 'name': 'Sales - Job Orders/Services', 'type': 'Revenue', 'classification': None, 'normal_balance': 'credit', 'parent': '40100'},
    {'code': '40103', 'name': 'Sales Returns and Allowances', 'type': 'Contra-Revenue', 'classification': None, 'normal_balance': 'debit', 'parent': '40100'},
    {'code': '40104', 'name': 'Sales Discounts', 'type': 'Contra-Revenue', 'classification': None, 'normal_balance': 'debit', 'parent': '40100'},
    {'code': '40200', 'name': 'Other Income', 'type': 'Other Income', 'classification': None, 'normal_balance': 'credit', 'parent': None},
    {'code': '40201', 'name': 'Interest Income', 'type': 'Other Income', 'classification': None, 'normal_balance': 'credit', 'parent': '40200'},
    {'code': '40202', 'name': 'Scrap Sales', 'type': 'Other Income', 'classification': None, 'normal_balance': 'credit', 'parent': '40200'},
    {'code': '40203', 'name': 'Gain on Sale of Property and Equipment', 'type': 'Other Income', 'classification': None, 'normal_balance': 'credit', 'parent': '40200'},
    {'code': '40204', 'name': 'Foreign Exchange Gain', 'type': 'Other Income', 'classification': None, 'normal_balance': 'credit', 'parent': '40200'},
    {'code': '40205', 'name': 'Rental Income', 'type': 'Other Income', 'classification': None, 'normal_balance': 'credit', 'parent': '40200'},
    {'code': '40206', 'name': 'Miscellaneous Income', 'type': 'Other Income', 'classification': None, 'normal_balance': 'credit', 'parent': '40200'},
    # ===== COST OF GOODS SOLD =====
    {'code': '50101', 'name': 'Cost of Goods Sold', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50110', 'name': 'Direct Materials', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50111', 'name': 'Direct Labor', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50120', 'name': 'Manufacturing Overhead', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50121', 'name': 'Indirect Materials', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50122', 'name': 'Indirect Labor', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50123', 'name': 'Factory Rent', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50124', 'name': 'Factory Utilities', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50125', 'name': 'Factory Supplies', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50126', 'name': 'Factory Repairs and Maintenance', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50127', 'name': 'Depreciation - Factory Equipment', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50128', 'name': 'Factory Insurance', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50129', 'name': 'Depreciation - Factory Building', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': '50120'},
    {'code': '50130', 'name': 'Other Manufacturing Overhead', 'type': 'Cost of Goods Sold', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    # ===== SELLING EXPENSE =====
    {'code': '50210', 'name': 'Selling and Distribution Expenses', 'type': 'Selling Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50211', 'name': 'Advertising and Promotion', 'type': 'Selling Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50210'},
    {'code': '50212', 'name': 'Freight Out and Delivery', 'type': 'Selling Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50210'},
    {'code': '50213', 'name': 'Sales Commission', 'type': 'Selling Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50210'},
    {'code': '50214', 'name': 'Sales Salaries and Wages', 'type': 'Selling Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50210'},
    # ===== ADMINISTRATIVE EXPENSE =====
    {'code': '50220', 'name': 'General and Administrative Expenses', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50221', 'name': 'Salaries and Wages', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50222', 'name': 'Employee Benefits', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50223', 'name': 'SSS, PhilHealth and Pag-IBIG Contributions', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50224', 'name': 'Rent Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50225', 'name': 'Utilities Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50226', 'name': 'Office Supplies Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50227', 'name': 'Communication Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50228', 'name': 'Repairs and Maintenance', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50229', 'name': 'Depreciation Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50230', 'name': 'Amortization Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50231', 'name': 'Insurance Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50232', 'name': 'Taxes and Licenses', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50233', 'name': 'Professional Fees', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50234', 'name': 'Transportation and Travel', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50235', 'name': 'Representation and Entertainment', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    {'code': '50236', 'name': 'Miscellaneous Expense', 'type': 'Administrative Expense', 'classification': None, 'normal_balance': 'debit', 'parent': '50220'},
    # ===== OTHER EXPENSE =====
    {'code': '50301', 'name': 'Interest Expense', 'type': 'Other Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50302', 'name': 'Bank Charges', 'type': 'Other Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50303', 'name': 'Foreign Exchange Loss', 'type': 'Other Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50304', 'name': 'Loss on Sale of Property and Equipment', 'type': 'Other Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50305', 'name': 'Cash Short/Over', 'type': 'Other Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    # ===== INCOME TAX EXPENSE =====
    {'code': '50401', 'name': 'Income Tax Expense - Current', 'type': 'Income Tax Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
    {'code': '50402', 'name': 'Income Tax Expense - Deferred', 'type': 'Income Tax Expense', 'classification': None, 'normal_balance': 'debit', 'parent': None},
]
