"""add cancel_reason to purchase_bills

Revision ID: 072ae8773591
Revises: 5ad857a1cba7
Create Date: 2026-06-10 13:46:25.153286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072ae8773591'
down_revision = '5ad857a1cba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_bills', schema=None) as batch_op:
        batch_op.drop_column('cancel_reason')

    # ### end Alembic commands ###
