"""Add user_branches junction table for multiple branch assignments

Revision ID: 18a7390d91a2
Revises: b21722a2caf1
Create Date: 2026-06-07 14:56:14.658685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a7390d91a2'
down_revision = 'b21722a2caf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_branches',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'branch_id')
    )

    # Data migration: Copy existing branch_id assignments to user_branches table
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT id, branch_id FROM users WHERE branch_id IS NOT NULL"
    ))

    for user_id, branch_id in result:
        connection.execute(sa.text(
            "INSERT INTO user_branches (user_id, branch_id, created_at) "
            "VALUES (:user_id, :branch_id, datetime('now'))"
        ), {'user_id': user_id, 'branch_id': branch_id})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_branches')
    # ### end Alembic commands ###
