"""add purchase_bill_attachments table

Revision ID: 194d567c5842
Revises: 6f74b4bf6af4
Create Date: 2026-06-11 17:13:13.432594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194d567c5842'
down_revision = '6f74b4bf6af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_bill_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['purchase_bills.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('purchase_bill_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_bill_attachments_bill_id'), ['bill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_bill_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_bill_attachments_bill_id'))

    op.drop_table('purchase_bill_attachments')
    # ### end Alembic commands ###
