"""Add vendor form fields (check_payee_name, postal_code, vat_category, wt checkboxes)

Revision ID: 45a87fbd46cd
Revises: cbc5028c522c
Create Date: 2026-06-01 19:17:34.372795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a87fbd46cd'
down_revision = 'cbc5028c522c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_payee_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_vat_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wt_wc010', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wt_wc011', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wt_wc100', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wt_wc158', sa.Boolean(), nullable=True))
        batch_op.drop_column('default_wt')
        batch_op.drop_column('default_vat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_vat', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('default_wt', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('wt_wc158')
        batch_op.drop_column('wt_wc100')
        batch_op.drop_column('wt_wc011')
        batch_op.drop_column('wt_wc010')
        batch_op.drop_column('default_vat_category')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('check_payee_name')

    # ### end Alembic commands ###
