"""Update audit_logs to support all action types and make user_id nullable

Revision ID: 4a8ce30aab16
Revises: 18a7390d91a2
Create Date: 2026-06-07 15:17:48.037159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8ce30aab16'
down_revision = '18a7390d91a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###

    # Data migration: Copy login_history entries to audit_logs
    connection = op.get_bind()

    # Get all login history records
    login_history = connection.execute(sa.text(
        "SELECT id, user_id, username, login_time, ip_address, user_agent, status, failure_reason "
        "FROM login_history ORDER BY login_time"
    ))

    for row in login_history:
        # Determine action based on status
        action = 'login_success' if row.status == 'success' else 'login_failed'

        # Prepare notes
        notes = f"Migrated from login_history. Username: {row.username}"
        if row.failure_reason:
            notes += f" | Reason: {row.failure_reason}"

        # Insert into audit_logs
        connection.execute(sa.text(
            "INSERT INTO audit_logs (module, action, record_id, record_identifier, user_id, "
            "timestamp, ip_address, user_agent, notes) "
            "VALUES (:module, :action, :record_id, :record_identifier, :user_id, "
            ":timestamp, :ip_address, :user_agent, :notes)"
        ), {
            'module': 'auth',
            'action': action,
            'record_id': row.user_id,
            'record_identifier': row.username,
            'user_id': row.user_id,
            'timestamp': row.login_time,
            'ip_address': row.ip_address,
            'user_agent': row.user_agent,
            'notes': notes
        })


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
