"""Add account approval workflow

Revision ID: 62a8aab0f00d
Revises: 3e45ac7ada83
Create Date: 2026-06-01 18:54:24.429059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a8aab0f00d'
down_revision = '3e45ac7ada83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('change_data', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_change_requests')
    # ### end Alembic commands ###
