"""add fiscal_year_closes table

Revision ID: 6fec6b362f43
Revises: 06354ca0c60d
Create Date: 2026-06-23 04:22:11.273134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fec6b362f43'
down_revision = '06354ca0c60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_year_closes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_entry_ids', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=False),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reopened_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year', 'branch_id', name='uq_fyc_year_branch')
    )
    with op.batch_alter_table('fiscal_year_closes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_year_closes_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_closes_fiscal_year'), ['fiscal_year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscal_year_closes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_year_closes_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_fiscal_year_closes_branch_id'))

    op.drop_table('fiscal_year_closes')
    # ### end Alembic commands ###
