"""add cash_disbursement_vouchers, cdv_ap_lines, cdv_expense_lines tables

Revision ID: 77c2e66f3325
Revises: 4412b44eb668
Create Date: 2026-06-14 15:36:27.880423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c2e66f3325'
down_revision = '4412b44eb668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_disbursement_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('cdv_number', sa.String(length=50), nullable=False),
    sa.Column('cdv_date', sa.Date(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_tin', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('check_bank', sa.String(length=100), nullable=True),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('total_ap_applied', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_wt', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_override', sa.Boolean(), nullable=False),
    sa.Column('wt_override', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('voided_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['cash_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_disbursement_vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_disbursement_vouchers_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_disbursement_vouchers_cdv_date'), ['cdv_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_disbursement_vouchers_cdv_number'), ['cdv_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cash_disbursement_vouchers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_disbursement_vouchers_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('cdv_ap_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdv_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('original_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['purchase_bills.id'], ),
    sa.ForeignKeyConstraint(['cdv_id'], ['cash_disbursement_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cdv_ap_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cdv_ap_lines_cdv_id'), ['cdv_id'], unique=False)

    op.create_table('cdv_expense_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdv_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_category', sa.String(length=100), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('wt_id', sa.Integer(), nullable=True),
    sa.Column('wt_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wt_amount', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cdv_id'], ['cash_disbursement_vouchers.id'], ),
    sa.ForeignKeyConstraint(['wt_id'], ['withholding_tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cdv_expense_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cdv_expense_lines_cdv_id'), ['cdv_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cdv_expense_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cdv_expense_lines_cdv_id'))

    op.drop_table('cdv_expense_lines')
    with op.batch_alter_table('cdv_ap_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cdv_ap_lines_cdv_id'))

    op.drop_table('cdv_ap_lines')
    with op.batch_alter_table('cash_disbursement_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_disbursement_vouchers_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_cash_disbursement_vouchers_status'))
        batch_op.drop_index(batch_op.f('ix_cash_disbursement_vouchers_cdv_number'))
        batch_op.drop_index(batch_op.f('ix_cash_disbursement_vouchers_cdv_date'))
        batch_op.drop_index(batch_op.f('ix_cash_disbursement_vouchers_branch_id'))

    op.drop_table('cash_disbursement_vouchers')
    # ### end Alembic commands ###
