"""Add TIN field to branches

Revision ID: 79720004a690
Revises: 3e45ac7ada83
Create Date: 2026-06-01 11:54:09.736719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79720004a690'
down_revision = '3e45ac7ada83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tin', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('tin')

    # ### end Alembic commands ###
