"""Add branch_id to sales_invoices, purchase_bills, receipts

Revision ID: 7e10975008c2
Revises: a1b2c3d4e5f6
Create Date: 2026-06-09 07:10:56.036323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e10975008c2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_bills_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key('fk_purchase_bills_branch_id', 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_receipts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key('fk_receipts_branch_id', 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_invoices_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_invoices_branch_id', 'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_invoices_branch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_invoices_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_receipts_branch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_receipts_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('purchase_bills', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_bills_branch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_bills_branch_id'))
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
