"""Add failed login tracking fields to User model

Revision ID: b9eea07a91c0
Revises: d07b418ec94d
Create Date: 2026-06-07 13:49:11.221823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9eea07a91c0'
down_revision = 'd07b418ec94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
