"""Add accounting periods table

Revision ID: d07b418ec94d
Revises: d2970dd6e023
Create Date: 2026-06-06 21:24:50.004066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07b418ec94d'
down_revision = 'd2970dd6e023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='unique_year_month')
    )
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_periods_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_periods_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_periods_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_periods_year'))
        batch_op.drop_index(batch_op.f('ix_accounting_periods_status'))
        batch_op.drop_index(batch_op.f('ix_accounting_periods_month'))

    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
