"""add vat_settlements table

Revision ID: d76332c9c780
Revises: d9bebfed48f3
Create Date: 2026-07-08 16:54:20.873598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76332c9c780'
down_revision = 'd9bebfed48f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output_vat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('input_vat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('prior_carryover', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_carryover', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('settlement_entry_ids', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=False),
    sa.Column('settled_by_id', sa.Integer(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['settled_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year', 'quarter', name='uq_vat_settlement_year_quarter')
    )
    with op.batch_alter_table('vat_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_settlements_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_settlements_quarter'), ['quarter'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vat_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_settlements_quarter'))
        batch_op.drop_index(batch_op.f('ix_vat_settlements_fiscal_year'))

    op.drop_table('vat_settlements')
    # ### end Alembic commands ###
