"""add units_of_measure table

Revision ID: d8ff3e02d0c0
Revises: 104d8f7b4cb0
Create Date: 2026-06-27 18:04:09.783662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ff3e02d0c0'
down_revision = '104d8f7b4cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_of_measure_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_of_measure_code'))

    op.drop_table('units_of_measure')
    # ### end Alembic commands ###
