"""vat_categories.input_vat_account_id (B-014)

Revision ID: dfc2126c99a8
Revises: ec961ef9cd13
Create Date: 2026-06-12 13:45:22.328305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc2126c99a8'
down_revision = 'ec961ef9cd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vat_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_vat_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vat_categories_input_vat_account_id', 'accounts', ['input_vat_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vat_categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vat_categories_input_vat_account_id', type_='foreignkey')
        batch_op.drop_column('input_vat_account_id')

    # ### end Alembic commands ###
