"""add request_reason to change request tables

Revision ID: ec961ef9cd13
Revises: 194d567c5842
Create Date: 2026-06-11 19:41:58.053430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec961ef9cd13'
down_revision = '194d567c5842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('vat_category_change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('withholding_tax_change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withholding_tax_change_requests', schema=None) as batch_op:
        batch_op.drop_column('request_reason')

    with op.batch_alter_table('vat_category_change_requests', schema=None) as batch_op:
        batch_op.drop_column('request_reason')

    with op.batch_alter_table('account_change_requests', schema=None) as batch_op:
        batch_op.drop_column('request_reason')

    # ### end Alembic commands ###
