"""add cash receipt voucher tables

Revision ID: ff59aff7c151
Revises: ap20260615rn01
Create Date: 2026-06-19 13:00:01.890149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff59aff7c151'
down_revision = 'ap20260615rn01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_receipt_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('crv_number', sa.String(length=50), nullable=False),
    sa.Column('crv_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_tin', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('check_bank', sa.String(length=100), nullable=True),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('total_ar_applied', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_wt', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_override', sa.Boolean(), nullable=False),
    sa.Column('wt_override', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('voided_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['cash_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_receipt_vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_receipt_vouchers_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_receipt_vouchers_crv_date'), ['crv_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_receipt_vouchers_crv_number'), ['crv_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cash_receipt_vouchers_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_receipt_vouchers_status'), ['status'], unique=False)

    op.create_table('crv_ar_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crv_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('original_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['crv_id'], ['cash_receipt_vouchers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crv_ar_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crv_ar_lines_crv_id'), ['crv_id'], unique=False)

    op.create_table('crv_revenue_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crv_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_category', sa.String(length=100), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('wt_id', sa.Integer(), nullable=True),
    sa.Column('wt_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wt_amount', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['crv_id'], ['cash_receipt_vouchers.id'], ),
    sa.ForeignKeyConstraint(['wt_id'], ['withholding_tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crv_revenue_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crv_revenue_lines_crv_id'), ['crv_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crv_revenue_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crv_revenue_lines_crv_id'))

    op.drop_table('crv_revenue_lines')
    with op.batch_alter_table('crv_ar_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crv_ar_lines_crv_id'))

    op.drop_table('crv_ar_lines')
    with op.batch_alter_table('cash_receipt_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_receipt_vouchers_status'))
        batch_op.drop_index(batch_op.f('ix_cash_receipt_vouchers_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cash_receipt_vouchers_crv_number'))
        batch_op.drop_index(batch_op.f('ix_cash_receipt_vouchers_crv_date'))
        batch_op.drop_index(batch_op.f('ix_cash_receipt_vouchers_branch_id'))

    op.drop_table('cash_receipt_vouchers')
    # ### end Alembic commands ###
