"""Purchase Requisition: add date_needed

Revision ID: prdate_0001
Revises: docrev_0002
Create Date: 2026-08-14

When the requested goods are wanted BY, distinct from request_date (when the
requisition was raised).

NULLABLE, and that is not a style preference: requisitions already exist -- one
in PhilGen's live database, two more in the local imports -- and a NOT NULL
column would demand a date be invented for them. Existing rows simply read blank.

Hand-written with batch ops because Migrate() is configured WITHOUT
render_as_batch, so autogenerated plain ALTER statements are not runnable on
SQLite. No FK here, so the unnamed-constraint trap that bites batch add_column
does not apply.
"""
import sqlalchemy as sa
from alembic import op

revision = 'prdate_0001'
down_revision = 'docrev_0002'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_needed', sa.Date(), nullable=True))


def downgrade():
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.drop_column('date_needed')
